/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Holding {
  'asset' : string,
  'purchaseDate' : Time,
  'saleHistory' : Array<SaleRecord>,
  'currentQuantity' : number,
  'quantity' : number,
  'costBasis' : [] | [number],
}
export interface SaleRecord {
  'quantitySold' : number,
  'salePrice' : number,
  'saleDate' : Time,
}
export type Time = bigint;
export interface Transaction {
  'shares' : number,
  'transactionType' : TransactionType,
  'pricePerShare' : [] | [number],
  'totalValue' : number,
  'date' : Time,
  'assetSymbol' : string,
}
export type TransactionType = { 'buy' : number } |
  { 'sell' : number };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addHolding' : ActorMethod<[string, number, [] | [number]], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculateProfitLoss' : ActorMethod<
    [],
    { 'totalProfitLoss' : number, 'totalSold' : bigint }
  >,
  'deleteHolding' : ActorMethod<[string], undefined>,
  'findHoldingsByAsset' : ActorMethod<[string], Array<Holding>>,
  'getAllHoldings' : ActorMethod<[], Array<Holding>>,
  'getAllTransactions' : ActorMethod<[], Array<Transaction>>,
  'getArchivedHoldings' : ActorMethod<[], Array<Holding>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFullArchive' : ActorMethod<[], Array<Holding>>,
  'getHolding' : ActorMethod<[string], [] | [Holding]>,
  'getHoldings' : ActorMethod<[], Array<Holding>>,
  'getTransactionHistory' : ActorMethod<[string], Array<Holding>>,
  'getUnsoldHoldings' : ActorMethod<[], Array<Holding>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordSale' : ActorMethod<[string, number, number], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateHolding' : ActorMethod<[string, number, [] | [number]], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];